name: Build and Package

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      # 2. 检查缓存
      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/roothide/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      # 3. 使用缓存
      - name: Use cache
        id: cache
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      # 4. 准备 Theos 环境
      - name: Prepare Theos
        uses: huami1314/theos-action@main

      # 5. 更新 SDK
      - name: Update SDK
        run: |
          XCODE_PATH=$(xcode-select -p)
          SDK_PATH="$XCODE_PATH/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
          THEOS_SDK_PATH="${{ github.workspace }}/theos/sdks/iPhoneOS.sdk"
          if [ ! -d "$THEOS_SDK_PATH" ]; then
            echo "Copying SDK from Xcode to Theos..."
            mkdir -p "${{ github.workspace }}/theos/sdks"
            cp -R "$SDK_PATH" "$THEOS_SDK_PATH"
          else
            echo "SDK already exists in Theos."
          fi

      # 6. 安装 GNU Make
      - name: Setup GNU Make
        run: |
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      # 7. 构建并打包
      - name: Build and Package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)

      # 8. 上传生成的 Deb 包
      - name: Upload Deb packages
        uses: actions/upload-artifact@v4.6.0
        with:
          name: BHTwitter-Deb-Packages
          path: ${{ github.workspace }}/packages/*.deb
